version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: liron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server/src
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/liron
    command: >
      bash -c "
        npm install &&
        npx sequelize-cli db:create &&
        npx sequelize-cli db:migrate &&
        npx sequelize db:seed:all &&
        npm run dev
      "

  frontend:
    build: ./client  
    ports:
      - "5173:5173"
    depends_on:
      - backend  

volumes:
  postgres_data:
